version: "3.0"

volumes:
  fuseki-data:
  django-data:
  repos:

services:

  fuseki:
    image: dockerogc/fuseki
    environment:
      ADMIN_PASSWORD: admin
      FUSEKI_DATASET_OGC_NA: ogc-na
      FUSEKI_INITIAL_DATA_OGC_NA: /initial-data/*.ttl
      FUSEKI_INITIAL_GRAPH_OGC_NA: "<urn:x-ogc:defs-server/initial-data>"
    ports:
      - "8002:3030"
    volumes:
      # Mount fuseki data volume for persistence
      - fuseki-data:/fuseki
      # Mount initial data repository for first run
      - ./fuseki-initial-data:/initial-data:ro

  vocprez:
    image: dockerogc/vocprez
    depends_on:
      - fuseki
    environment:
      SYSTEM_URI_BASE: http://defs-dev.opengis.net/vocprez
      SPARQL_ENDPOINT: http://fuseki:3030/ogc/query
      DOCKER_REVERSE_PROXY: "/vocprez:8000"
      DOCKER_REVERSE_PROXY_HEADERS: "SCRIPT_NAME=/vocprez"
    ports:
      - "8001:8000"

  django:
    image: dockerogc/ogc-django
    volumes:
      # Mount django data volume for persistence
      - django-data:/app/django
      # Uncomment the following entry to load dev modules
      # - ./django-modules-dev.json:/app/django-modules.json

  nginx:
    image: python:3.9-alpine
    depends_on:
      - fuseki
      - vocprez
      - django
      - repos-cron
    environment:
      DOCKER_PROXY: |
        [
          { "location": "/vocprez", "service": "vocprez", "port": 8000, "headers": { "SCRIPT_NAME": "/vocprez" } },
          { "location": "/ogc-na", "repo": "ogc-na" }
        ]
    entrypoint: python
    command: ['/nginx/nginx-entrypoint.py']
    volumes:
      - ./nginx:/nginx
      - django-data:/var/django:ro
      - repos:/var/repos:ro
    ports:
      - "8000:80"

  repos-cron:
    image: dockerogc/git-cron
    environment:
      - "CRON_REPO_ogc_na=https://github.com/opengeospatial/NamingAuthority.git ogc-na"
    volumes:
      - repos:/repos
